#!/bin/bash 


#Check Root privileges, if not, operation with sudo or su prefix.
verify_root_priv() {
    if [ ! $EUID -eq 0 ]; then
        echo "Please run this script by root privileges."
        exit 1
    fi
}

secure_sshd() {
    sed -i 's/^#Port 22/Port 54321/g' /etc/ssh/sshd_config
    sed -i 's/^#PermitRootLogin\s*yes$/PermitRootLogin no/g' /etc/ssh/sshd_config
    sed -i 's/^#PubkeyAuthentication\s*yes$/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
}


add_new_user() {
    os_dist_name=""
    #read os-release info
    if [ -r /etc/os-release ]; then
        os_dist_name="$(. /etc/os-release && echo "$ID")"
    fi
    useradd $os_dist_name
    mkdir /home/$os_dist_name/.ssh -p
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj3sFcfqI0ybPHSsdyFbV7+yKmWr562meCPqbisIUGy8qYDkrtjZ6e+uREAyww824HLTMhAp6qMzqekUqVelgUgtTJa/PH59ggsXVDuF3/h8pYvNMCtOo+RCHFcXLmvXUKmuUJ1xJx6qaFDH5IGA3uJakoyXQgZNCU3o6aXCKuZ3E8zATrmOJ7MMd5pyJRYSfwd3VdCL3p4MTf4zWXcJZc00i+SC34ME04qG8owqIoJ//UkMJZs7eHamV3gi+TwqU0pWH4kTNVrljncANcSnWKbsAcIkHPy4BfglzQJGJZQSeENQU5xD+MgPvxSBARhLvUsNwlz5wBpGLCk6yd2R8H" >> /home/$os_dist_name/.ssh/authorized_keys
    chmod 755 /home/$os_dist_name/.ssh
    chown $os_dist_name:$os_dist_name /home/$os_dist_name/.ssh
    chown $os_dist_name:$os_dist_name /home/$os_dist_name/.ssh/authorized_keys
    chmod 600 /home/$os_dist_name/.ssh/authorized_keys
    echo "%$os_dist_name     ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
}


main() {
    verify_root_priv
    secure_sshd
    add_new_user
}

main